version: "3.8"
services:
  mongo:
    restart: always
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo
    entrypoint: node dist/src/server.js -e development

volumes:
  mongo_volume:
